---
output: html_document
---


# Introduction to Probability and Simulation {#ch4}

> "All life is an experiment. The more experiments you make, the better." 
>
> --- Ralph Waldo Emerson



<div class="objective-container">
<div class="objectives"> Learning objectives </div>
1. Conceptual understanding of randomness and simulation
2. Learn the scientific definition of probability
3. Methods for calculating probabilities
</div>

## Randomness and Simulation {#ch4_s1}

In this section, we seek to understand randomness and how we can use the computer 
to quickly simulate an outcome. To do this, we will start with a dice game in which two dies are
rolled. Rolling dice is an example of a **random process**, because we cannot 
predict the outcome with certainty. By contrast, a process that is not random is 
known as **deterministic**, as the outcome is determined beforehand. An example 
of a deterministic process would be computing the area of a triangle from its
base and height - the area is always $\frac{1}{2} * base * height$.

In our dice game, we are interested in the sum total of the roll. For example, if a 2 
and a 6 are rolled, the sum total is 8. Each die has 6 outcomes, so there are 36 
possible ways to roll the two die:

<center>
<table align="center">
<tbody><tr> <td>(1,1) </td><td> (1,2) </td><td> (1,3) </td><td> (1,4) </td><td> (1,5) </td><td> (1,6) </td></tr>
<tr> <td>(2,1) </td><td> (2,2) </td><td> (2,3) </td><td> (2,4) </td><td> (2,5) </td><td> (2,6) </td></tr>
<tr> <td>(3,1) </td><td> (3,2) </td><td> (3,3) </td><td> (3,4) </td><td> (3,5) </td><td> (3,6) </td></tr>
<tr> <td>(4,1) </td><td> (4,2) </td><td> (4,3) </td><td> (4,4) </td><td> (4,5) </td><td> (4,6) </td></tr>
<tr> <td>(5,1) </td><td> (5,2) </td><td> (5,3) </td><td> (5,4) </td><td> (5,5) </td><td> (5,6) </td></tr>
<tr> <td>(6,1) </td><td> (6,2) </td><td> (6,3) </td><td> (6,4) </td><td> (6,5) </td><td> (6,6) </td></tr>
</tbody></table>
</center>



<div class="exercise-container">
<div class="exercise"> &nbsp; </div>

There are 11 possible sum totals you can achieve when rolling two six-sided dies,
{2, 3, 4, ..., 11, 12}. In this game, you win if your roll adds up to 7.

1.	Out of the 36 possible rolls listed above, how many rolls result in a win? What does this tell you about the chance of winning the game?

2.	Using the applet, play the game 30 times and fill out the table below with whether you won and rolled a 7 (W) or lost and rolled any other total (L).

<iframe src="https://ph-ivshiny.iowa.uiowa.edu/ceward/textbook/shinyApps/singleDieRoll" width = "100%" height = "500"> 
</iframe>


<table border="1" cellspacing="0" cellpadding="0" >
<tbody>
<tr>
<td valign="top" ><p>Game </p></td>
<td valign="top" ><p>1</p></td>
<td valign="top" ><p>2</p></td>
<td valign="top" ><p>3</p></td>
<td valign="top" ><p>4</p></td>
<td valign="top" ><p>5</p></td>
<td valign="top" ><p>6</p></td>
<td valign="top" ><p>7</p></td>
<td valign="top" ><p>8</p></td>
<td valign="top" ><p>9</p></td>
<td valign="top" ><p>10</p></td>
<td valign="top" ><p>11</p></td>
<td valign="top" ><p>12</p></td>
<td valign="top" ><p>13</p></td>
<td valign="top" ><p>14</p></td>
<td valign="top" ><p>15</p></td>
</tr>

<tr>
<td valign="top" ><p>Result</p></td>
<td valign="top" > </td>
<td valign="top" > </td>
<td valign="top" > </td>
<td valign="top" > </td>
<td valign="top" > </td>
<td valign="top" > </td>
<td valign="top" > </td>
<td valign="top" > </td>
<td valign="top" > </td>
<td valign="top" > </td>
<td valign="top" > </td>
<td valign="top" > </td>
<td valign="top" > </td>
<td valign="top" > </td>
<td valign="top" > </td>
</tr>

<tr>
<td valign="top" ><p>Game </p></td>
<td valign="top" ><p>16</p></td>
<td valign="top" ><p>17</p></td>
<td valign="top" ><p>18</p></td>
<td valign="top" ><p>19</p></td>
<td valign="top" ><p>20</p></td>
<td valign="top" ><p>21</p></td>
<td valign="top" ><p>22</p></td>
<td valign="top" ><p>23</p></td>
<td valign="top" ><p>24</p></td>
<td valign="top" ><p>25</p></td>
<td valign="top" ><p>26</p></td>
<td valign="top" ><p>27</p></td>
<td valign="top" ><p>28</p></td>
<td valign="top" ><p>29</p></td>
<td valign="top" ><p>30</p></td>
</tr>

<tr>
<td valign="top" ><p>Result</p></td>
<td valign="top" > </td>
<td valign="top" > </td>
<td valign="top" > </td>
<td valign="top" > </td>
<td valign="top" > </td>
<td valign="top" > </td>
<td valign="top" > </td>
<td valign="top" > </td>
<td valign="top" > </td>
<td valign="top" > </td>
<td valign="top" > </td>
<td valign="top" > </td>
<td valign="top" > </td>
<td valign="top" > </td>
<td valign="top" > </td>
</tr>

</tbody>
</table>


3.	What proportion of times did you win the game? Was this close to what you 
  expected? Why or why not?

</div>


While this was a relatively simple dice game, it illustrates several important concepts.
Going into the game, we are able to determine how likely it is that we win. We did 
this by first enumerating all possible outcomes of two dies being rolled. Any such collection 
of all possible outcomes of a random process is called the **sample space**. Then,
we considered the ways we could observe the **event** that the two rolls result 
in a sum total of 7. In general, an event is an outcome or collection of outcomes 
from a random process and will always be contained in the sample space. 

Another important observation is that we have not physically rolled any dice ourselves.
Instead, we have used the computer to perform a **simulation**. Simulations are
a powerful tool which allow us to quickly and consistently repeat a random process.
There are two components to simulation:  

1. The conditions and behavior of the experiment are determined in advance through
  the **simulation parameters**.  
  
2. The experiment is performed with the aid of a computer.

In the dice rolling simulation, the parameters specified that each side of the die
were equally likely and that two dies were rolled each time the game was played.
These parameters were specified internally, such that the user cannot alter the 
specifications. Later in this chapter, we will work with simulations where the 
parameters can be changed. Lastly, the use of the computer may seem trivial, but 
it has two important implications:we were able to exactly specify the simulation
parameters, and we are able to repeat *this exact same experiment* knowing all 
conditions will remain exactly the same.


<div class="definition-container">
<div class="definition"> &nbsp;  </div>

**Random Process: ** <em> An act or process that results in an outcome that cannot be predicted with certainty. </em>

**Deterministic Process: ** <em> An act or process that results in an outcome that is not random. </em>

**Sample Space: ** <em> The set of all possible outcomes from a random process. </em>

**Event: ** <em> An outcome or collection of outcomes from a random process. </em>

**Simulation: ** <em> A tool to replicate random processes an arbitrary number of times. </em>

**Simulation Parameters: ** <em> Values which change the behavior of the simulation. </em>
</div>



## Probability {#ch4_s2}

Statistical inference is founded in the ability to quantify uncertainty. Probability
is the mechanism that allows us to do so, by telling us how likely something is to happen.
People talk loosely about probability all the time. For example, "What's the 
chance of rain tomorrow?" or "How likely is it that drug A is better than drug B?"
In order for probability to be used for statistical inference, we must be precise
about our definition of probability.

We would all agree that the probability of heads when flipping a fair coin is 50% 
and the probability of rolling a 2 on a 6-sided die is 1/6, but why is that true? 
Well, if we were to flip a coin many, many times, we would expect half of the 
flips to result in heads. Similarly, if we roll a 6-sided die over and over, 1/6 
of the rolls should result in a value of 2. The big idea is that when we talk
about probability, we are thinking about a *long-run frequency* or what will 
happen if the random process is repeated over and over again under the same 
conditions. If we think about probabilities in terms of the long-run frequencies, 
we can define and quantify **probability** as the fraction of time an event 
occurs if a random process is repeated indefinitely. This means that 
probabilities are always between 0 and 1, since we can never observed more 
or less events than the number of times the process is repeated, e.g. we can never 
observed 12 heads on 10 coin flips. 

This leads us to some important properties of probabilities:

<div class="equation-container">
<div class="equation"> Properties of Probability </div>
1) The sum of probabilities for all outcomes in the sample space, $\mathcal{S}$,
  must equal 1
2) For any event, the probability of that event is the sum of the probabilities 
  for all the outcomes in that event
</div>

Consider flipping a fair coin three times. Each act of flipping the coin is 
random process - the coin might land on heads and it might land on tails. 
Letting $H$ be shorthand for the flip resulting in heads and $T$ be shorthand 
for the flip resulting in tails, the sample space can be enumerated as 

$$\mathcal{S} = \{HHH, HHT, HTH, THH, TTH, THT, HTT, TTT\},$$ 

giving us eight possible results from the three coin flips. Since each outcome 
is equally likely (why?) The first property tells us that the probability of any
specific outcome (say, $HHH$) is 1/8. The second tells us that the probability 
of heads on the first toss is $4/8 = 1/2$, since four of the eight possible 
outcomes have heads on the first toss ($\{HHH, HHT, HTH, HTT\}$ ). These 
properties underlie a lot of the more complicated formulas and concepts we will
cover in this chapter, although we don't always think about them explicitly. 

<div class="exercise-container">
<div class="exercise"> &nbsp; </div>


We will now investigate the long-run frequency definition of probability using
an applet which simulates coin flipping. Internally, the simulation parameters
specify that each coin flip has a 50\% chance of heads. As a user, you are able
to determine how many coin flips you would like to perform. The simulation 
results are summarized in three figures:

1. (Top right) the flip results are shown with a blue "T" indicating the flip 
resulted in tails and a pink "H" indicating the flip resulted in heads.

2. (Bottom left) the total number of heads and tails across all flips is tallied.

3. (Bottom right)  the running total of the proportion of heads is plotted. For 
example, if we flip a coin three times and observe THH, the running proportion 
of heads is 0/1=0 after the first flip (T), 1/2=0.5 after the second flip (TH), 
and 2/3=0.67 after the third flip (THH). The dotted red line on this plot falls 
at 0.5, which translates to half of the flips resulting in heads.


<iframe src="https://ph-ivshiny.iowa.uiowa.edu/ceward/textbook/shinyApps/singleCoinFlip" width = "100%" height = "900"> 
</iframe>

<ol>
 <li>Set the number of flips to 10 and click the &quot;Flip Coins&quot; button 
 15 times. Each time you perform an experiment, record the number of heads you 
 observed in the following table:
 
 <table border="1" cellspacing="0" cellpadding="0" >
<tbody>
<tr>
<td valign="top" ><p>Trial </p></td>
<td valign="top" ><p>1</p></td>
<td valign="top" ><p>2</p></td>
<td valign="top" ><p>3</p></td>
<td valign="top" ><p>4</p></td>
<td valign="top" ><p>5</p></td>
<td valign="top" ><p>6</p></td>
<td valign="top" ><p>7</p></td>
<td valign="top" ><p>8</p></td>
<td valign="top" ><p>9</p></td>
<td valign="top" ><p>10</p></td>
<td valign="top" ><p>11</p></td>
<td valign="top" ><p>12</p></td>
<td valign="top" ><p>13</p></td>
<td valign="top" ><p>14</p></td>
<td valign="top" ><p>15</p></td>
</tr>

<tr>
<td valign="top" ><p># Heads</p></td>
<td valign="top" > </td>
<td valign="top" > </td>
<td valign="top" > </td>
<td valign="top" > </td>
<td valign="top" > </td>
<td valign="top" > </td>
<td valign="top" > </td>
<td valign="top" > </td>
<td valign="top" > </td>
<td valign="top" > </td>
<td valign="top" > </td>
<td valign="top" > </td>
<td valign="top" > </td>
<td valign="top" > </td>
<td valign="top" > </td>
</tr>



</tbody>
</table>
 <ol>
 <li>On any given experiment where the coin is flipped 10 times, how many flips would you expect to result in heads? Why?</li>
 <li>How many times did you see <em>exactly</em> four heads? What about at least two heads?</li>
 </ol>
 </li>
 <li>Now set the number of flips to 100 and click the &quot;Flip Coins&quot; button.
 <ol>
 <li>What happens to the running proportion of heads as the coin is continually flipped?</li>
 <li>Focusing your attention on the plot of the running proportion of heads, click the &quot;Flip Coins&quot; button several times. What do you notice about the plot? What characteristics of the plot stay the same and what differ?</li>
 </ol>
 </li>
 <li>For each of the following number of coin flips, perform one experiment and record the final <em>proportion&nbsp;</em>of heads you observed (e.g., 12 heads out of 20 flips = 12/20 =0.6).<br><br>
 <table>
 <tbody>
 <tr>
 <td>3:
 <td>5:
 <td>10:
 </tr>
 <tr>
 <td>20:
 <td>100:
 <td>500:
 </tr>
 <tr>
 <td>1,000:
 <td>5,000:
 <td>10,000:
 </tr>
 </tbody>
 </table>
 <ol>
 <li>What happens to the proportion of heads you observed as the number of flips increased? 
  How does this relate to the concept of long-run frequency?</li>
 <li>How does the final proportion of heads observed relate to the probability of observing heads?</li>
 </ol>
 </li>
</ol>

</div>


<div class="definition-container">
<div class="definition"> &nbsp;  </div>

**Probability: ** <em> The fraction of times an event occurs when a random process is repeated indefinitely.</em>

</div>


## Methods for Computing Probabilities {#ch4_s3}

There are several methods that can be used to compute probabilities. We will
introduce these methods in the context of coin flipping and seeking to answer 
the question: if a coin is flipped three times, what is the probability that 
exactly two of the coins will be heads?

<ol type = "1">
<li> **Enumeration Method:** The enumeration method proceeds by listing all of
the possible outcomes of the experiment and counting the total number of ways
the event can be observed. Then, the probability is calculated as:

$$\text{Probability} = \dfrac{\text{Number of ways event can occur}}{\text{Total number of outcomes}}$$
In our coin flipping example, we know the sample space includes eight outcomes:

$$
\mathcal{S} = \{HHH, HHT, HTH, HTT, THH, TTH, THT, TTT\}
$$

Next, we count how many of those have exactly two heads:

$$
\mathcal{S} = \{HHH, \color{red}{HHT}, \color{red}{HTH}, \color{red}{THH}, TTH, THT, HTT, TTT\}
$$

Dividing the events of interest by the total number of outcomes, we see that the 
probability of getting exactly two heads is
$P(\text{# Heads = 2}) = \frac{\text{# Heads = 2}}{\text{# Possible Outcomes}} = \frac38$. 

That is, by enumerating the eight possible outcomes, we identified three of them 
in which the number of heads was two. </li>
<br>
<li> **Probability function method:** Often, a random process has an associated 
*probability function* that allows us to determine the probability of a set of 
outcomes. In this case, our coin flipping example follows what is known as a
*binomial distribution*, which has the probability function:

$$
P(\text{# Heads = k}) = f(k; n,p) = \binom{n}{k}p^k(1-p)^{n-k}.
$$
For our experiment, the probability of heads is $p = 0.5$, the total number of 
flips is $n = 3$, and for our event, $k = 2$ heads. Substituting these numbers, 
we have"

$$
\begin{align*}
P(\text{# Heads = 2}) &= \binom{3}{2} (0.5)^2 (0.5)^{3-2} \\
&= 3 \times (0.5)(0.5)(0.5) \\
&= 0.375.
\end{align*}
$$
We see, then, that a probability function is a function that takes an event as
an argument and returns an associated probability. Just as in the enumeration
method, we find that $P(\text{# Heads = 2}) = 0.375 = \frac38$. </li>

<li> **Simulation method:** The previous methods are valid, but can quickly 
become impractical or even impossible once the problem grows becomes more complex.
Even for an example as simple as coin flipping, the 
enumeration method can quickly become infeasible. As the number of flips increases, 
the size of the sample space increases exponentially, making it challenging (or
lengthy) to count all possible outcomes and all the ways the event can occur. If
we seek to use the probability function method, we must know what the function is; 
for complex processes, these functions can be nearly impossible to construct, 
leaving statisticians and researchers with no clear way to specify the probability of events.

The simulation method allows us to mitigate both problems by using the computer
to repeatedly perform an experiment (say 10,000 times), and computing the
proportion of experiments in which the event was observed. We have previously defined
probability as the fraction of times the event occurs if the random process is repeated
many times. This is exactly what the simulation method does.

Mathematically, this looks like

$$
P(\# \text{ Heads} = 2) \approx \frac{\text{Number of times \{# Heads = 2\} } }{\text{# Experiments}}
$$
A careful reader might note that for a given random experiment (such as flipping 
a coin three times) and a specified event (exactly two heads), there is only a
single* correct answer to the question, "What is the probability of getting
exactly two heads when flipping a coin three times?", and this single correct 
answer is precisely what was found using the enumeration and probability
function methods described above. contrast, The simulation method provides an 
approximation to the probability, as opposed to an exact calculation. However,
as the number of repeated experiments increases, the simulation method will give
a result closer and closer to the true answer.


</li>

</ol>



<div class="exercise-container">
<div class="exercise"> &nbsp; </div>

<iframe src="https://ph-ivshiny.iowa.uiowa.edu/ceward/textbook/shinyApps/coinFlipSimulation" width = "100%" height = "400"> 
</iframe>

</div>


<div class="definition-container">
<div class="definition"> &nbsp;  </div>

**Enumeration method: ** <em> A method to exactly compute probabilities by dividing 
  the number of ways an event can occur by the total number of possible outcomes. </em>

**Probability function method: ** <em> A method to exactly compute probabilities
  by using a known function. </em>

**Simulation method: ** <em> A method to approximately compute probabilities by
  repeatedly simulating experiments and taking the proportion of simulations where
  the event occurs.</em>

</div>
















