--- 
title: "An Intuitive, Interactive, Introduction to Biostatistics"
author: "Caitlin Ward and Collin Nolte"
site: bookdown::bookdown_site
output: 
  bookdown::gitbook:
    css: "style.css"
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: ceward/introTextbook
description: ""
---

> "Statistics is, or should be, about scientific investigation and how to do it better, but many statisticians believe it is a branch of mathematics."
>
> --- George E. P. Box

```{r, eval = FALSE}
library(magrittr)
library(scales)
# devtools::install_github("hadley/emo")
library(emo) # for emojis
bookdown::render_book('index.Rmd', 'bookdown::gitbook')
```


# Introduction {-}

Welcome! This resource offers an interactive learning experience for introductory
biostatistics. This resource was designed with the course BIOS:4120 Introduction
to Biostatistics at the University of Iowa in mind, but could be used in any 
introductory statistics or biostatistics course. We combine textual explanations
and embedded interactive Shiny applications, to provide students with an engaging
learning resource that offers an intuitive illustration of core statistical 
concepts. The applications and associated exercises are targeted at
*conceptional* understanding, as opposed to calculations.

At this point in time, we provide chapters on:

* Introduction to biostatistics
* Data and data summaries
* Study design and bias
* Randomness, probability, and simulation
* Probability distributions
* Sampling distributions and Central Limit Theorem
* Confidence intervals and hypothesis testing


<!-- ::: {.infobox .hazard data-latex="hazard"} -->
<!-- This resource is in a Beta phase -->
<!-- ::: -->



## Acknowledgements

We would like to acknowledge the funding which made the creation of this 
resource possible, provided by a University of Iowa Libraries OpenHawks grant.

We would also like to thank Patrick Breheny, Knute Carter, and Jacob Oleson 
whose course notes helped inform some of the material covered in this textbook.


